version: '3'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55w0rd2022"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  commander-api:
    image: nasifmahmood/commanderapi
    environment:
      DBServer: "ms-sql-server"
    ports:
      - "8080:80"